<?php
/**
 * System autoload logics.
 *
 * @author		Belikhun
 * @since		1.0.0
 * @license		https://tldrlegal.com/license/mit-license MIT
 *
 * Copyright (C) 2018-2023 Belikhun. All right reserved
 * See LICENSE in the project root for license information.
 */

namespace Blink\Autoload;

use Blink\Middleware\Exception\ClassNotDefined;
use Blink\Middleware\Exception\InvalidDefinition;
use function Blink\fileGet;
use function Blink\filePut;
use function Blink\getFiles;
use function Blink\getRelativePath;
use function Blink\Handlers\ExceptionHandler;

global $AUTOLOAD_DATA, $AUTOLOAD_MAP, $AUTOLOADED;
$AUTOLOAD_DATA = array();
$AUTOLOAD_MAP = array();
$AUTOLOADED = array();

function updateAutoloadData() {
	global $AUTOLOAD_DATA, $AUTOLOAD_MAP;

	// Namespace regex
	$nsre = "/namespace ([a-zA-Z0-9\\\\]+);/mi";

	// Class name regex
	$clre = '/^(?:[\t\n]*|[\t\n]*abstract\s+|[\t\n]*final\s+)(?:class|trait|enum|interface) ([a-zA-Z0-9\_]+)[\\a-zA-Z0-9\ \,\t\n]*\{/m';

	foreach (\CONFIG::$INCLUDES as $include) {
		if (!file_exists($include))
			continue;

		$files = getFiles($include, "php");

		foreach ($files as $file) {
			$path = getRelativePath($file -> getPathname());
			$hash = md5($path);

			if (!empty($AUTOLOAD_MAP[$hash]))
				continue;

			$content = fileGet(($path[0] === "/" && !str_starts_with($path, BASE_PATH))
				? BASE_PATH . $path
				: $path);

			$namespace = "";
			$classes = array();

			if (!preg_match_all($clre, $content, $clmatches))
				continue;

			if (preg_match($nsre, $content, $nsmatch))
				$namespace = trim($nsmatch[1]);

			foreach ($clmatches[1] as $match)
				$classes[] = trim($match);

			$AUTOLOAD_MAP[$hash] = array();

			foreach ($classes as $class) {
				$fullname = !empty($namespace)
					? "{$namespace}\\{$class}"
					: $class;

				$AUTOLOAD_DATA[$fullname] = array(
					"path" => $path,
					"hash" => $hash,
					"namespace" => $namespace,
					"class" => $class,
					"name" => $fullname
				);

				$AUTOLOAD_MAP[$hash][] = $fullname;
			}
		}
	}
}

function getAutoloadData() {
	global $AUTOLOAD_DATA, $AUTOLOAD_MAP;
	$path = DATA_ROOT . "/autoload.php";

	if (!file_exists($path))
		return;

	// Time to include our autoload data.
	$AUTOLOAD_DATA = require $path;

	foreach ($AUTOLOAD_DATA as $class => $value)
		$AUTOLOAD_MAP[$value["hash"]] = $class;
}

function saveAutoloadData() {
	global $AUTOLOAD_DATA;

	$lines = array(
		"<?php",
		"",
		"// Autoload file generated by Blink ✨",
		"",
		"return array("
	);

	foreach ($AUTOLOAD_DATA as $key => $value) {
		$values = [];

		foreach ($value as $vk => $vv) {
			if (is_numeric($vv))
				$vv = (string) $vv;
			else if (is_bool($vv))
				$vv = $vv ? "true" : "false";
			else if ($vv === null)
				$vv = "null";
			else
				$vv = "'{$vv}'";

			$values[] = "'$vk' => {$vv}";
		}

		$lines[] = "\t'{$key}' => [ " . implode(", ", $values) . " ],";
	}

	$lines[] = ");";
	$lines[] = "";
	filePut(DATA_ROOT . "/autoload.php", implode("\n", $lines));
}

function handlers() {
	$class = "Handlers";
	$default = CORE_ROOT . "/defaults/Handlers.php";
	$appPath = BASE_PATH . "/includes/Handlers.php";

	require_once CORE_ROOT . "/includes/Handlers.php";

	if (file_exists($appPath))
		require_once $appPath;
	else
		require_once $default;

	// Make sure the class have been included and defined correctly.
	if (!class_exists($class)) {
		require_once $default;
		throw new \Blink\Exception\ClassNotDefined($class, $appPath);
	}

	if (!in_array("Blink\\Handlers", class_parents($class, false)))
		throw new \Blink\Exception\InvalidDefinition($class, "Blink\\Handlers", $appPath);

	return true;
}

function middleware(string $class) {
	$name = explode("\\", $class);
	$name = end($name);

	$corePath = CORE_ROOT . "/middleware/{$name}.php";
	$default = CORE_ROOT . "/defaults/middleware/{$name}.php";
	$appPath = BASE_PATH . "/middleware/{$name}.php";
	$parent = "Blink\\Middleware\\{$name}";

	// Verify if this class has been defined in core.
	if (!file_exists($corePath))
		return false;

	$fallback = function () use ($default, $name) {
		if (!file_exists($default)) {
			// Create new default file for this class.
			$content = fileGet(CORE_ROOT . "/defaults/middleware/.template");
			$content = str_replace("{{NAME}}", $name, $content);
			$content = "<?php\n{$content}";
			filePut($default, $content);
		}

		require_once $default;
	};

	// Include the base class first to avoid error in the.
	// future.
	require_once $corePath;

	if (file_exists($appPath)) {
		require_once $appPath;
	} else {
		// Fallback to default middleware definition file.
		$fallback();
	}

	// Make sure the class have been included and defined correctly.
	if (!class_exists($class)) {
		$fallback();
		throw new ClassNotDefined($class, $appPath);
	}

	if (!in_array("Blink\\Middleware\\{$name}", class_parents($class, false))) {
		// We can't redefine the class because it's included, so
		// no fallback call here.
		throw new InvalidDefinition($class, $parent, $appPath);
	}

	return true;
}

function callMiddleware($class) {
	if (!class_exists("Blink\\Middleware", false))
		require_once CORE_ROOT . "/middleware/Middleware.php";

	if (\Blink\Middleware::disabled())
		return false;

	try {
		return \Middleware\Autoload::load($class);
	} catch (\Throwable $e) {
		\Blink\Middleware::disable();

		if (str_contains($class, "Exception")) {
			// We are autoloading an exception class here,
			// let it die gracefully.
			return false;
		}

		throw $e;
	}
}

function AutoloadClass(string $class) {
	global $AUTOLOAD_DATA, $AUTOLOADED;

	if (str_starts_with($class, "Middleware")) {
		if (defined("DISABLE_MIDDLEWARE_INCLUDE"))
			return;

		try {
			// Process middleware class include.
			if (middleware($class))
				return;
		} catch (\Throwable $e) {
			// Include failed! disable middleware autoloading.
			define("DISABLE_MIDDLEWARE_INCLUDE", true);

			ExceptionHandler($e);
			return;
		}
	}

	if ($class === "Handlers") {
		if (defined("DISABLE_HANDLERS_INCLUDE"))
			return;

		try {
			// Try to include global handlers.
			handlers();
			return;
		} catch (\Throwable $e) {
			// Include failed! disable handlers autoloading.
			define("DISABLE_HANDLERS_INCLUDE", true);

			ExceptionHandler($e);
			return;
		}
	}

	if (callMiddleware($class))
		return;

	if (empty($AUTOLOAD_DATA))
		getAutoloadData();

	if (!empty($AUTOLOAD_DATA[$class])) {
		$item = $AUTOLOAD_DATA[$class];
		$path = ($item["path"][0] === "/" && !str_starts_with($item["path"], BASE_PATH))
			? BASE_PATH . $item["path"]
			: $item["path"];

		if (file_exists($path)) {
			require_once $path;

			if (class_exists($class)) {
				$AUTOLOADED[] = $item;
				return;
			}
		}

		// This class might have been moved to other location or deleted.
		// Unset this class data and start fallback autoloading.
		unset($AUTOLOAD_DATA[$class]);
	}

	// We might have a new class here that the code is requesting. Update the
	// autoload cache and try again.
	updateAutoloadData();
	saveAutoloadData();

	if (!empty($AUTOLOAD_DATA[$class])) {
		$item = $AUTOLOAD_DATA[$class];
		require_once ($item["path"][0] === "/") ? BASE_PATH . $item["path"] : $item["path"];
		return;
	}
}

spl_autoload_register("Blink\\Autoload\\AutoloadClass");
